<a href="https://colab.research.google.com/github/Abhiie/ML_Lab/blob/main/Lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
predicts whether a person buys computer or not.

In [3]:
#import libraries
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
# reading the csv file, del 2 columns from the file, checking first few rows of the file
data=pd.read_csv('/content/drive/MyDrive/BuyComputer/BuyComputer.csv')
print(data)
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

      User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
y = data.iloc[: , -1].values
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [5]:
import pandas as pd
data=pd.read_csv('BuyComputer.csv')
x = data.iloc[:,:-1].values
print(x)

[[15624510       19    19000]
 [15810944       35    20000]
 [15668575       26    43000]
 ...
 [15654296       50    20000]
 [15755018       36    33000]
 [15594041       49    36000]]


In [6]:
y = data.iloc[: , -1].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data,y,random_state=98)
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(x_train[0])
w = []
b = 0.2
print(len_x)

4


In [7]:
entries = len(x_train[:,0])
entries

300

In [8]:
for weights in range(len_x):
  w.append(0)
w

[0, 0, 0, 0]

In [9]:
# Sigmoid function
import numpy as np
def sigmoid(z):
  return 1.0/(1 + np.exp(-np.dot(z, b)))


def predict(inputs):
  pred_prob = sigmoid(inputs)
  pred_value = np.where(pred_prob >= .5, 1, 0)
  return np.squeeze(pred_value)

In [10]:
#Loss function
def loss_func(y,a):
  log_func_v = sigmoid(y)
  print(log_func_v)
  a = np.squeeze(a)
  step1 = a * np.log(log_func_v)
  step2 = (1 - a) * np.log(1 - log_func_v)
  final = -step1 - step2
  return np.mean(final)
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)
for i in range(3000):
  y_pred = predict(x_train[0])
  print(y_pred)
l_pred = predict(y)
for i in range(len(y)):
  print("predicted: " + str(l_pred[i]) + " actual: " + str(y[i]))
from sklearn import metrics

print(metrics.classification_report(y, l_pred))

[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]
[1 1 0 1]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 98)
LR.fit(x_train,y_train)

LogisticRegression(random_state=98)

In [12]:
prediction = LR.predict(x_test)
print(prediction)

[1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1
 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0
 0 1 1 0 1 0 0 1 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1]


In [13]:
from sklearn import metrics

print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        58
           1       1.00      1.00      1.00        42

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [30]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [15]:
mnist.y_onehot = True
print('Train: x:{}, y:{}'.format(len(x_train),y_train.shape))

Train: x:60000, y:(60000,)
