<a href="https://colab.research.google.com/github/Abhiie/ML_Lab/blob/main/Lab8_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

     |████████████████████████████████| 462 kB 5.0 MB/s 


In [ ]:
import gensim
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am",
"an", "and", "any", "are", "as", "at", "be", "because", "been", "before",
"being", "below", "between", "both", "but", "by", "could", "did", "do",
"does", "doing", "down", "during", "each", "few", "for", "from", "further",
"had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here",
"here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i",
"i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its",
"itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on",
"once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out",
"over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so",
"some", "such", "than", "that", "that's", "the", "their", "theirs", "them",
"themselves", "then", "there", "there's", "these", "they", "they'd",
"they'll", "they're", "they've", "this", "those", "through", "to", "too",
"under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're",
"we've", "were", "what", "what's", "when", "when's", "where", "where's",
"which", "while", "who", "who's", "whom", "why", "why's", "with", "would",
"you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself",
"yourselves" ]
datasets = pd.read_csv('/spam1.csv')
print("\nData :\n",datasets)
print("\nData statistics\n",datasets.info())


Data :
        v1                                                 v2
0    spam  Free entry in 2 a wkly comp to win FA Cup fina...
1    spam  FreeMsg Hey there darling it's been 3 week's n...
2    spam  WINNER!! As a valued network customer you have...
3    spam  Had your mobile 11 months or more? U R entitle...
4    spam  SIX chances to win CASH! From 100 to 20,000 po...
..    ...                                                ...
508  spam  This is the 2nd time we have tried 2 contact u...
509   ham              Will �_ b going to esplanade fr home?
510   ham  Pity, * was in mood for that. So...any other s...
511   ham  The guy did some bitching but I acted like i'd...
512   ham                         Rofl. Its true to its name

[513 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 513 entries, 0 to 512
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      513 non-null    object
 1   v2      513 non-nu

In [ ]:
#countvectorize
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am",
"an", "and", "any", "are", "as", "at", "be", "because", "been", "before",
"being", "below", "between", "both", "but", "by", "could", "did", "do",
"does", "doing", "down", "during", "each", "few", "for", "from", "further",
"had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here",
"here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i",
"i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its",
"itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on",
"once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out",
"over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so",
"some", "such", "than", "that", "that's", "the", "their", "theirs", "them",
"themselves", "then", "there", "there's", "these", "they", "they'd",
"they'll", "they're", "they've", "this", "those", "through", "to", "too",
"under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're",
"we've", "were", "what", "what's", "when", "when's", "where", "where's",
"which", "while", "who", "who's", "whom", "why", "why's", "with", "would",
"you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself",
"yourselves" ]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(stopwords)
vectorizer.get_feature_names_out()

array(['about', 'above', 'after', 'again', 'against', 'all', 'am', 'an',
       'and', 'any', 'are', 'as', 'at', 'be', 'because', 'been', 'before',
       'being', 'below', 'between', 'both', 'but', 'by', 'could', 'did',
       'do', 'does', 'doing', 'down', 'during', 'each', 'few', 'for',
       'from', 'further', 'had', 'has', 'have', 'having', 'he', 'her',
       'here', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'if',
       'in', 'into', 'is', 'it', 'its', 'itself', 'let', 'll', 'me',
       'more', 'most', 'my', 'myself', 'nor', 'of', 'on', 'once', 'only',
       'or', 'other', 'ought', 'our', 'ours', 'ourselves', 'out', 'over',
       'own', 're', 'same', 'she', 'should', 'so', 'some', 'such', 'than',
       'that', 'the', 'their', 'theirs', 'them', 'themselves', 'then',
       'there', 'these', 'they', 'this', 'those', 'through', 'to', 'too',
       'under', 'until', 'up', 've', 'very', 'was', 'we', 'were', 'what',
       'when', 'where', 'which', 'while', 'who', 'whom'

In [ ]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [ ]:
#word2vec
import pandas as pd
text = pd.read_csv("/spam1.csv")
text.head()

v1                                                 v2
0  spam  Free entry in 2 a wkly comp to win FA Cup fina...
1  spam  FreeMsg Hey there darling it's been 3 week's n...
2  spam  WINNER!! As a valued network customer you have...
3  spam  Had your mobile 11 months or more? U R entitle...
4  spam  SIX chances to win CASH! From 100 to 20,000 po...

In [ ]:
text.shape

(513, 2)

In [ ]:
#training of word2vec
def read_questions(row,column_name):
    return gensim.utils.simple_preprocess(str(row[column_name]).encode('utf-8'))
    
documents = []
for index, row in text.iterrows():
    documents.append(read_questions(row,"v1"))
    if row["v1"] == "spam":
        documents.append(read_questions(row,"v2"))

print("List of lists. Let's confirm: ", type(documents), " of ", type(documents[0]))

List of lists. Let's confirm:  <class 'list'>  of  <class 'list'>


In [ ]:
#Model
model = gensim.models.Word2Vec(size=150, window=10, min_count=2, sg=1, workers=10)
model.build_vocab(documents)

In [ ]:
word_vectors = model.wv
count = 0
for word in word_vectors.vocab:
    if count<100:
        print(word)
        count += 1
    else:
        break

spam
free
entry
in
wkly
to
win
fa
final
st
may
text
receive
std
txt
rate
apply
over
freemsg
hey
there
it
been
week
now
and
no
word
back
like
some
you
up
for
still
send
rcv
winner
as
valued
network
customer
have
selected
prize
reward
claim
call
code
valid
hours
only
had
your
mobile
months
or
more
entitled
update
the
latest
colour
mobiles
with
camera
co
on
cash
from
pounds
cost
day
days
reply
hl
info
urgent
won
our
www
net
pobox
ldnw
use
credit
click
wap
next
message
here
http
com
england
dont
miss
team
news
ur
national


In [ ]:
len(word_vectors.vocab)

456

In [ ]:
vector = model.wv["ur"]  # numpy vector of a word
len(vector)

150

In [ ]:
vector

array([ 1.8800157e-03,  8.5878361e-04, -3.1462945e-03,  7.3581294e-05,
       -1.2865233e-03,  2.6836125e-03, -1.5166178e-04, -4.2674501e-04,
       -9.4404671e-04, -3.2885275e-03,  1.6852898e-03, -1.8651868e-03,
       -8.1691949e-04,  8.8860700e-04,  1.8066126e-03,  2.9454746e-03,
        2.0767208e-03, -1.5645793e-03, -2.5212350e-03,  1.0239240e-03,
       -2.2594340e-03, -1.1544683e-03,  2.0002315e-03, -1.7342877e-03,
        3.0327690e-04,  2.7635521e-03,  2.9506502e-03,  1.3233812e-03,
        2.1357143e-03, -2.9766064e-03, -2.9988859e-03,  2.3481441e-03,
       -1.2006271e-03,  2.2308130e-03, -5.2727218e-04,  1.4596795e-04,
       -1.9247410e-03,  4.3317990e-04, -7.8775670e-04, -9.3588058e-04,
        1.4627987e-03,  2.2289124e-03, -2.3087973e-03, -2.5966296e-03,
        6.1191327e-04, -1.2354398e-03, -3.2005219e-03,  7.1603770e-04,
       -3.0232246e-03, -1.7084097e-03,  4.8107203e-04, -1.7701730e-03,
       -1.6983654e-03,  9.4676932e-04, -1.1869681e-03,  2.3800172e-03,
      